//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NewsRoom.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_NEWSROTYPE                  129
#define IDB_TOOL_NEWSPOT                130
#define IDB_TOOL_EDIT_SPOT              131
#define IDB_TOOL_CUT                    132
#define IDB_TOOL_EDIT                   133
#define IDB_TREE_SPOT                   134
#define IDB_TREE_FOLDER_SPOT            135
#define IDB_TOOL_NEWTRAFFICSCHEDULE     136
#define IDB_TREE_FOLDER_SCHEDULE        137
#define IDB_TREE_SCHEDULE               138
#define IDB_TREE_SOUNDRECORDING         139
#define IDB_TOOL_QUERYBLOCKS            140
#define IDB_TREE_RECORDINGTASK          141
#define IDD_RMS                         142
#define IDB_CONTAINER_JINGLES           142
#define IDD_TEXT                        143
#define IDD_NEWCARTWALL                 144
#define IDB_TREE_JINGLE                 145
#define IDD_NEWSLINEUP                  145
#define IDB_TREE_NEWSLINEUP             146
#define IDB_RECOFF                      147
#define IDB_PLAY                        148
#define IDD_RADIOSTATION                148
#define IDD_RMONAIR                     149
#define IDB_TOOL_NEWNEWSLINEUP          149
#define IDB_TOOL_PFL                    150
#define IDB_STOP                        151
#define IDB_TOOL_NEWSOUND               152
#define IDB_TREE_USER                   153
#define IDB_TOOL_NEWRM                  154
#define IDB_BITMAP1                     155
#define IDB_TREE_RM                     156
#define IDB_TREE_FOLDER_RM              157
#define IDB_CONTAINER_TRAFFIC           158
#define IDB_TREE_TEXT                   159
#define IDB_TREE_FOLDER_TEXT            160
#define IDB_TOOL_NEWTEXT                161
#define IDB_TOOL_NEWCARTWALL            162
#define IDB_TREE_CARTWALL               163
#define IDB_REC                         181
#define IDB_PAUSE_BIG                   184
#define IDB_CONTAINER_MUSIC             185
#define IDB_CONTAINER_VOICEINSERT       191
#define IDB_CONTAINER_RMS               201
#define IDS_TOOL_NEWSPOT                512
#define IDS_TOOL_EDIT                   513
#define IDS_TOOL_CUT                    514
#define IDS_TOOL_NEWTRAFFICSCHEDULE     515
#define IDS_TOOL_QUERYBLOCKS            516
#define IDS_TOOL_NEWSOUND               517
#define IDS_TOOL_PFL                    518
#define IDS_TOOL_NEWRM                  519
#define IDS_TOOL_NEWTEXT                520
#define IDS_TOOL_NEWLINEUP              521
#define IDC_RM_NAME                     1000
#define IDC_RM_TYPE                     1001
#define IDC_TYPE                        1001
#define IDC_RM_DATE                     1002
#define IDC_NAME                        1002
#define IDC_RM_KEYWORDS                 1003
#define IDC_TEXTTYPE                    1003
#define IDC_RM_PATH                     1004
#define IDC_RM_FILENAME                 1005
#define IDC_DATE                        1005
#define IDC_RM_OBS                      1006
#define IDC_TEXT                        1006
#define IDC_KEYWORDS                    1007
#define IDC_NEWS                        1011
#define IDC_LIST2                       1013
#define IDC_REMOVE                      1014
#define IDC_MOVEDOWN                    1015
#define IDC_MOVEUP                      1016
#define IDC_LINEUP                      1018
#define IDC_STARTINGDATE                1053
#define IDC_ENDINGDATE                  1054
#define IDS_TRAFFICSCHEDULE             2048
#define IDS_CUSTOMERSPOTS               2049
#define IDS_SPOTSTOSCHEDULE             2050
#define IDS_AIRINGPERIOD                2051
#define IDS_AIRINGDAYS                  2052
#define IDS_SUN                         2053
#define IDS_MON                         2054
#define IDS_TUE                         2055
#define IDS_WED                         2056
#define IDS_THU                         2057
#define IDS_FRI                         2058
#define IDS_SAT                         2059
#define IDS_BLOCKS                      2060
#define IDS_SELECTEDBLOCKS              2061
#define IDS_POSITION                    2062
#define IDS_SPOTSNUMBER                 2063
#define IDS_SPOTSLENGTH                 2064
#define IDS_BLOCK                       2065
#define IDS_EMPTYSLOT                   2066
#define IDS_REFRESH                     2067
#define IDS_SPONSORS                    2068
#define IDS_RECORDINGS                  2069
#define IDS_VOICEINSERT                 2070
#define IDS_RMSMANAGEMENT               2071
#define IDS_ONAIRRMS                    2072
#define IDS_TEXTMANAGEMENT              2073
#define IDS_ONAIRTEXT                   2074
#define IDS_NEWSLINEUP                  2075
#define IDS_RMLINEUP                    2076
#define IDS_FORMAT_FROMTO               4096
#define IDS_MENUSTART                   6146
#define IDS_MENUFADEIN                  6147
#define IDS_MENUINTRO                   6148
#define IDS_MENUFADEOUT                 6149
#define IDS_MENUMIX                     6150
#define IDS_MENUEND                     6151
#define IDS_MENULOOPA                   6152
#define IDS_MENULOOPB                   6153
#define IDS_CONFIRMSCHEDULEREMOVE       8192
#define IDS_CONFIRMSPONSORREMOVE        8193
#define IDS_CANTDELETECUSTOMER          8194
#define IDS_CONFIRMCUSTOMERREMOVE       8195
#define IDS_CONFIRMSPOTREMOVE           8196
#define IDS_NEWCUSTOMER                 8197
#define IDS_NEWBUSINESS                 8198
#define IDS_NEWAGENCY                   8199
#define IDS_NEWVOICE                    8200
#define IDS_NEWSALESMAN                 8201
#define IDS_SPONSORALLREADYEXISTS       8202
#define IDS_NEWTYPEOFRM                 8203
#define IDS_CONFIRMRMREMOVE             8204
#define IDS_RMALLREADYEXISTS            8205
#define IDS_CONFIRMTEXTREMOVE           8206
#define IDS_TEXTALLREADYEXISTS          8207
#define IDS_NEWTEXT                     8208
#define IDS_CONFIRMRMLINEUPREMOVE       8209
#define IDS_CONFIRMNEWSLINEUPREMOVE     8210
#define IDS_CONFIRMRECORDING            8211
#define IDS_TIMESIGNAL                  8212
#define ID_TRAFFIC                      32771
#define ID_RMS                          32771
#define ID_RMSONAIR                     32772
#define ID_RMSLINEUP                    32773
#define ID_VIEW_AGENCY                  32774
#define ID_TEXT                         32774
#define ID_VIEW_SALESMAN                32775
#define ID_TEXTONAIR                    32775
#define ID_NEWSLINEUP                   32776
#define ID_VIEW_VERTICAL                32777
#define ID_VIEW_HORIZONTAL              32778
#define ID_HELP_HELP                    32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
