//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Manager.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_MANAGETYPE                  129
#define IDB_TOOL_NEWSPOT                130
#define IDB_TOOL_EDIT_SPOT              131
#define IDD_ONAIRUSER                   131
#define IDB_TOOL_CUT                    132
#define IDB_TOOL_EDIT                   133
#define IDB_TREE_SPOT                   134
#define IDB_TREE_FOLDER_SPOT            135
#define IDB_TOOL_NEWTRAFFICSCHEDULE     136
#define IDB_TREE_FOLDER_SCHEDULE        137
#define IDB_TREE_SCHEDULE               138
#define IDB_TREE_SOUNDRECORDING         139
#define IDB_TOOL_QUERYBLOCKS            140
#define IDB_TREE_RECORDINGTASK          141
#define IDB_TREE_FOLDER                 142
#define IDB_TREE_FOLDER_JINGLE          143
#define IDD_FOLDER                      143
#define IDB_TOOL_NEWJINGLE              144
#define IDB_TREE_JINGLE                 145
#define IDB_TREE_NEWSLINEUP             146
#define IDB_TOOL_NEWFOLDER              147
#define IDD_TIME                        148
#define IDB_TOOL_NEWNEWSLINEUP          149
#define IDD_RADIOSTATION                149
#define IDB_TOOL_PFL                    150
#define IDD_SYSTEMUSER                  150
#define IDD_NATIONALITIES               151
#define IDB_TOOL_NEWSOUND               152
#define IDD_NATIONALITY                 152
#define IDB_TREE_USER                   153
#define IDD_EXPRESSIONS                 153
#define IDB_TOOL_NEWRM                  154
#define IDD_EXPRESSION                  154
#define IDB_TOOL_NEWBLOCK               155
#define IDD_DIALOG_ERC                  155
#define IDB_TREE_RM                     156
#define IDD_DIALOG_ERC_CREATE           156
#define IDB_TREE_FOLDER_RM              157
#define IDB_TREE_TEXT                   159
#define IDB_TREE_FOLDER_TEXT            160
#define IDB_TOOL_NEWTEXT                161
#define IDB_TOOL_NEWCARTWALL            162
#define IDB_TREE_CARTWALL               163
#define IDB_TREE_FOLDER_MUSIC           164
#define IDB_TREE_FOLDER_UNLISTED        165
#define IDB_TREE_MUSIC                  166
#define IDB_TOOL_NEWPLAYLIST            167
#define IDB_TOOL_SAVE                   169
#define IDB_TREE_TEMPLATE               170
#define IDB_TREE_LOCK                   176
#define IDB_TOOL_LOCK                   177
#define IDB_TREE_NEWTEMPLATE            179
#define IDB_TREE_FOLDERUSER             180
#define IDS_TOOL_NEWSPOT                512
#define IDS_TOOL_EDIT                   513
#define IDS_TOOL_CUT                    514
#define IDS_TOOL_NEWSCHEDULE            515
#define IDS_STRING515                   515
#define IDS_TOOL_QUERYBLOCKS            516
#define IDS_STRING516                   516
#define IDS_TOOL_NEWSOUND               517
#define IDS_STRING517                   517
#define IDS_TOOL_PFL                    518
#define IDS_STRING518                   518
#define IDS_TOOL_NEWRM                  519
#define IDS_TOOL_NEWTEXT                520
#define IDS_STRING520                   520
#define IDS_TOOL_NEWLINEUP              521
#define IDS_STRING521                   521
#define IDS_TOOL_NEWJINGLE              522
#define IDS_STRING522                   522
#define IDS_TOOL_NEWBLOCK               523
#define IDS_STRING523                   523
#define IDS_TOOL_NEWPLAYLIST            524
#define IDS_STRING524                   524
#define IDS_TOOL_EDITLINEUP             525
#define IDS_STRING525                   525
#define IDS_TOOL_SAVE                   526
#define IDS_STRING526                   526
#define IDS_TOOL_LOCK                   527
#define IDS_STRING527                   527
#define IDS_TOOL_NEWFOLDER              528
#define IDS_TOOL_NEWTIME                529
#define IDC_NAME                        1000
#define IDC_PASS1                       1001
#define IDC_PASS2                       1002
#define IDC_SCHEDULE                    1003
#define IDC_MUSICEDITING                1004
#define IDC_PATH                        1004
#define IDC_SOUNDRECORDER               1005
#define IDC_MUSIC                       1005
#define IDC_FOLDER                      1005
#define IDC_BLOCKS                      1006
#define IDC_JINGLES                     1006
#define IDC_SPOTS                       1007
#define IDC_RMS                         1008
#define IDC_DISCOGRAPHY                 1008
#define IDC_TAKES                       1009
#define IDC_NEWMUSIC                    1009
#define IDC_TIME                        1010
#define IDC_EDITMUSIC                   1010
#define IDC_PRODUCER                    1011
#define IDC_DELETEMUSIC                 1011
#define IDC_ONAIRMANAGMENT              1012
#define IDC_LIST2                       1013
#define IDC_JINGLES_NEW                 1013
#define IDC_JINGLES_EDIT                1014
#define IDC_JINGLES_CUT                 1015
#define IDC_JINGLES_ONAIR               1016
#define IDC_BLOCKS_ADD                  1017
#define IDC_BLOCKS_EDIT                 1018
#define IDC_BLOCKS_CUT                  1019
#define IDC_PLAYLISTADD                 1020
#define IDC_PLAYLISTEDIT                1021
#define IDC_PLAYLISTEDITCONTENT         1022
#define IDC_PLAYLISTCUT                 1023
#define IDC_TRAFFIC                     1024
#define IDC_SPOTS_NEW                   1025
#define IDC_SPOTS_EDIT                  1026
#define IDC_TRAFFIC_VIEW                1027
#define IDC_SPONSORS                    1028
#define IDC_USER                        1029
#define IDC_TRAFFIC_ADD                 1030
#define IDC_TRAFFIC_EDIT                1031
#define IDC_RMS_ADD                     1032
#define IDC_SPOTS_CUT                   1033
#define IDC_SCHEDULER                   1034
#define IDC_LINEUP_ADD                  1035
#define IDC_LINEUP_EDIT                 1036
#define IDC_LINEUP_CUT                  1037
#define IDC_CRITERIA_ADD                1038
#define IDC_CRITERIA_EDIT               1039
#define IDC_CRITERIA_CUT                1040
#define IDC_VOICE_ADD                   1041
#define IDC_VOICE_EDIT                  1042
#define IDC_VOICE_CUT                   1043
#define IDC_AUTO_SCHEDULE               1044
#define IDC_EDIT_SCHEDULE               1045
#define IDC_NEWSROOM                    1046
#define IDC_RMS_EDIT                    1047
#define IDC_RMS_CUT                     1048
#define IDC_RMS_ONAIR                   1049
#define IDC_RMS_LINEUP                  1050
#define IDC_TEXT_NEW                    1051
#define IDC_TEXT_EDIT                   1052
#define IDC_TEXT_CUT                    1053
#define IDC_TEXT_ONAIR                  1054
#define IDC_TEXT_LINEUP                 1055
#define IDC_TRAFFIC_CUT                 1056
#define IDC_MANAGER_USER                1057
#define IDC_MANAGER_FOLDERS             1058
#define IDC_MANAGER_TIME                1059
#define IDC_LIST                        1059
#define IDC_MANAGER_LOG                 1060
#define IDC_NATIONALITY                 1060
#define IDC_INSTRUMENTALS               1061
#define IDC_CODE                        1061
#define IDC_ACTIV                       1062
#define IDC_UE                          1063
#define IDC_EXPRESSION                  1065
#define IDC_START                       1068
#define IDC_END                         1069
#define IDC_CHOOSEFOLDER                1070
#define IDC_STATION                     1072
#define IDC_LIST1                       1073
#define IDS_TRAFFICSCHEDULE             2048
#define IDS_CUSTOMERSPOTS               2049
#define IDS_SPOTSTOSCHEDULE             2050
#define IDS_AIRINGPERIOD                2051
#define IDS_AIRINGDAYS                  2052
#define IDS_SUN                         2053
#define IDS_MON                         2054
#define IDS_TUE                         2055
#define IDS_WED                         2056
#define IDS_THU                         2057
#define IDS_FRI                         2058
#define IDS_SAT                         2059
#define IDS_BLOCKS                      2060
#define IDS_SELECTEDBLOCKS              2061
#define IDS_POSITION                    2062
#define IDS_SPOTSNUMBER                 2063
#define IDS_SPOTSLENGTH                 2064
#define IDS_BLOCK                       2065
#define IDS_EMPTYSLOT                   2066
#define IDS_REFRESH                     2067
#define IDS_SPONSORS                    2068
#define IDS_RECORDINGS                  2069
#define IDS_VOICEINSERT                 2070
#define IDS_RMSMANAGEMENT               2071
#define IDS_ONAIRRMS                    2072
#define IDS_TEXTMANAGEMENT              2073
#define IDS_ONAIRTEXT                   2074
#define IDS_NEWSLINEUP                  2075
#define IDS_RMLINEUP                    2076
#define IDS_JINGLESMANAGEMENT           2077
#define IDS_ONAIRJINGLES                2078
#define IDS_BLOCKSMANAGEMENT            2079
#define IDS_JINGLES                     2080
#define IDS_SPOTS                       2081
#define IDS_TIMESIGNAL                  2082
#define IDS_PLAYLISTMANAGEMENT          2083
#define IDS_DISCOGRAPHY                 2084
#define IDS_NOTLISTED                   2085
#define IDS_JANUARY                     2086
#define IDS_FEBRUARY                    2087
#define IDS_STRING2088                  2088
#define IDS_STRING2089                  2089
#define IDS_STRING2090                  2090
#define IDS_STRING2091                  2091
#define IDS_STRING2092                  2092
#define IDS_STRING2093                  2093
#define IDS_STRING2094                  2094
#define IDS_STRING2095                  2095
#define IDS_STRING2096                  2096
#define IDS_STRING2097                  2097
#define IDS_MONTHS                      2098
#define IDS_DAYS                        2099
#define IDS_SCHEDULES                   2100
#define IDS_LINEUP                      2101
#define IDS_TEMPLATE                    2102
#define IDS_MUSIC                       2103
#define IDS_NEW                         2104
#define IDS_IRRELEVANTCRITERIA          2105
#define IDS_LASTSCHEDULE                2106
#define IDS_RMS                         2107
#define IDS_NEWVOICEINSERT              2108
#define IDS_LENGTH                      2109
#define IDS_INTRO                       2110
#define IDS_TIME                        2111
#define IDS_PATH                        2112
#define IDS_TAKES                       2113
#define IDS_PRODUCER                    2114
#define IDS_NAME                        2115
#define IDS_FOLDER                      2116
#define IDS_ONAIRLOG                    2117
#define IDS_FOLDERMANAGMENT             2118
#define IDS_TIMESIGNALDEFINITION        2119
#define IDS_ONAIRUSERS                  2120
#define IDS_SYSTEMUSERS                 2121
#define IDS_ONAIRMANAGEMENT             2122
#define IDS_FORMAT_FROMTO               4096
#define IDS_MENUSTART                   6146
#define IDS_MENUFADEIN                  6147
#define IDS_MENUINTRO                   6148
#define IDS_MENUFADEOUT                 6149
#define IDS_MENUMIX                     6150
#define IDS_MENUEND                     6151
#define IDS_MENULOOPA                   6152
#define IDS_MENULOOPB                   6153
#define IDS_CONFIRMSCHEDULEREMOVE       8192
#define IDS_CONFIRMSPONSORREMOVE        8193
#define IDS_CANTDELETECUSTOMER          8194
#define IDS_CONFIRMCUSTOMERREMOVE       8195
#define IDS_CONFIRMSPOTREMOVE           8196
#define IDS_NEWCUSTOMER                 8197
#define IDS_NEWBUSINESS                 8198
#define IDS_NEWAGENCY                   8199
#define IDS_NEWVOICE                    8200
#define IDS_NEWSALESMAN                 8201
#define IDS_SPONSORALLREADYEXISTS       8202
#define IDS_NEWTYPEOFRM                 8203
#define IDS_CONFIRMRMREMOVE             8204
#define IDS_RMALLREADYEXISTS            8205
#define IDS_CONFIRMTEXTREMOVE           8206
#define IDS_TEXTALLREADYEXISTS          8207
#define IDS_NEWTEXT                     8208
#define IDS_CONFIRMRMLINEUPREMOVE       8209
#define IDS_CONFIRMNEWSLINEUPREMOVE     8210
#define IDS_CONFIRMJINGLEREMOVE         8211
#define IDS_NEWTYPEOFJINGLE             8212
#define IDS_JINGLEALLREADYEXISTS        8213
#define IDS_CONFIRMBLOCKREMOVE          8214
#define IDS_CONFIRMPLAYLISTREMOVE       8215
#define IDS_CONFIRMREMOVERECORDINGTASK  8216
#define IDS_INVALIDCRITERIA             8217
#define IDS_INVALIDJINGLECRITERIA       8218
#define IDS_CONFIRMMUSICTEMPLATEREMOVE  8219
#define IDS_CONFIRMJINGLETEMPLATEREMOVE 8220
#define IDS_CONFIRMVOICEINSERTREMOVE    8221
#define IDS_SCHEDULECONFLICT            8222
#define IDS_CONFIRMRECORDING            8223
#define IDS_CONFIRMUSERREMOVE           8224
#define IDS_CONFIRMTIMEREMOVE           8225
#define IDS_FORMAT_SCHEDULETO           10000
#define ID_TRAFFIC                      32771
#define ID_ONAIRUSER                    32771
#define ID_JINGLES_ONAIR                32772
#define ID_VIEW_VERTICAL                32772
#define ID_BLOCKS_MANAGEMENT            32773
#define ID_VIEW_HORIZONTAL              32773
#define ID_VIEW_AGENCY                  32774
#define ID_FOLDERS                      32774
#define ID_VIEW_SALESMAN                32775
#define ID_TIMESIGNAL                   32775
#define ID_NEWSLINEUP                   32776
#define ID_LOG                          32776
#define ID_TIME                         32777
#define ID_USERS                        32780
#define ID_TABELAS_NACIONALIDADES       32782
#define ID_TABELAS_EXPRESS32783         32783
#define ID_TABLES_NATIONALITIES         32784
#define ID_TABLES_EXPRESSIONS           32785
#define ID_CONSULTAS_LOG                32786
#define ID_CONSULTAS_LISTAGEMERC        32787
#define ID_EXPORT_ERC                   32788
#define ID_LISTAGENS_ERC                32789
#define ID_LIST_ERC                     32790
#define ID_ERC_CRIAR                    32791
#define ID_ERC_CONSULGAR                32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
