//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InStoreMedia.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_INSTORTYPE                  129
#define IDD_DIALOG1                     132
#define IDB_LOGO                        133
#define IDD_MUSICSEARCH                 133
#define IDB_TREE_SPOT                   134
#define IDD_JINGLE                      134
#define IDB_REFRESH                     135
#define IDB_REFRESH_HOT                 136
#define IDB_MUSICFOLDER                 137
#define IDB_MUSICSMALL                  138
#define IDB_TREE_SOUNDRECORDING         139
#define IDB_NEWFOLDER                   140
#define IDB_CONTAINER_MUSIC             141
#define IDB_CONTAINER_JINGLES           142
#define IDB_CONTAINER_LINEUP            143
#define IDB_CUE                         144
#define IDB_GARBAGE                     145
#define IDB_TREE_NEWSLINEUP             146
#define IDB_JINGLESMALL                 147
#define IDB_PLAY                        148
#define IDB_RENAME                      149
#define IDB_UNCUE                       150
#define IDD_EDITFILENAME                150
#define IDB_STOP                        151
#define IDB_MIX                         152
#define IDB_PAUSE_ON                    153
#define IDB_PAUSE_OFF                   154
#define IDB_LOOP_ON                     155
#define IDB_LOOP_OFF                    156
#define IDB_CONTAINER_PRODUCER          157
#define IDB_CONTAINER_TRAFFIC           158
#define IDB_PFL                         159
#define IDB_TREE_FOLDER_TEXT            160
#define IDB_INFO                        161
#define IDB_INFO_HOT                    162
#define IDB_MOVEUP                      163
#define IDB_MOVEUP_HOT                  164
#define IDB_MOVEDOWN                    165
#define IDB_MOVEDOWN_HOT                166
#define IDB_THUMB_VOL                   167
#define IDB_MANUAL                      168
#define IDD_PLAYLIST                    168
#define IDB_AUTOMATIC                   169
#define IDB_LIVE                        170
#define IDB_CONTAINER_CARTWALL          171
#define IDB_NEW_SOUND                   172
#define IDB_CONTAINER_MUSICFOLDER       173
#define IDB_CONTAINER_MUSICSEARCH       174
#define IDB_CONTAINER_SCHEDULING        175
#define IDB_DISCARD                     176
#define IDB_SAVE                        178
#define IDB_LOAD                        179
#define IDB_NEW                         180
#define IDB_REC                         181
#define IDB_PAUSE_BIG                   184
#define IDB_SPOT                        187
#define IDB_CONTAINER_BLOCKS            188
#define IDB_CONTAINER_VOICEINSERT       191
#define IDB_VOICEINSERT                 192
#define IDB_NEWSCHEDULE                 193
#define IDB_SORTASC                     196
#define IDB_SORTDESC                    197
#define IDB_CONTAINER_AIRED             198
#define IDB_CONTAINER_INTERNET          200
#define IDB_CONTAINER_RMS               201
#define IDB_CUT                         203
#define IDB_CONTAINER_BUMPED            207
#define IDB_BACK                        208
#define IDB_EDIT                        224
#define IDB_EXIT                        225
#define IDB_FOWARD                      226
#define IDB_LOCK                        227
#define IDB_RECOFF                      228
#define IDB_TIMESIGNAL                  229
#define IDB_TREE_LOCK                   230
#define IDB_TREE_CARTWALL               231
#define IDB_TREE_FOLDER_JINGLE          232
#define IDB_TREE_FOLDER_MUSIC           233
#define IDB_TREE_FOLDER_RM              234
#define IDB_TREE_FOLDER_SCHEDULE        235
#define IDB_TREE_FOLDER_SPOT            236
#define IDB_TREE_FOLDER_UNLISTED        237
#define IDB_TREE_JINGLE                 238
#define IDB_TREE_MUSIC                  239
#define IDB_TREE_RECORDINGTASK          240
#define IDB_TREE_RM                     241
#define IDB_TREE_SCHEDULE               242
#define IDB_TREE_TEXT                   243
#define IDB_TREE_USER                   244
#define IDC_TITLE                       1000
#define IDC_ARTIST                      1001
#define IDC_CATEGORY                    1004
#define IDC_PLAYLIST                    1005
#define IDC_EXPRESSION                  1006
#define IDC_JINGLETYPE                  1006
#define IDC_JINGLENAME                  1007
#define IDC_JINGLERYTHM                 1008
#define IDC_JINGLERYTHMTXT              1009
#define IDC_COMBO1                      1009
#define IDC_JINGLEFOLDER                1010
#define IDC_JINGLEFILE                  1011
#define IDC_EDIT1                       1028
#define IDC_CHECK1                      1029
#define IDS_SUNDAY                      10000
#define IDS_MONDAY                      10001
#define IDS_TUESDAY                     10002
#define IDS_WEDNESDAY                   10003
#define IDS_THURSDAY                    10004
#define IDS_FRIDAY                      10005
#define IDS_SATURDAY                    10006
#define IDS_REFRESH                     10007
#define IDS_INFO                        10008
#define IDS_REMOVE                      10009
#define IDS_PFL                         10010
#define IDS_MOVEUP                      10011
#define IDS_MOVEDOWN                    10012
#define IDS_NEWSOUND                    10013
#define IDS_NEWCART                     10014
#define IDS_SAVECART                    10015
#define IDS_LOADCART                    10016
#define IDS_DISCARD                     10017
#define IDS_NEWSCHEDULE                 10018
#define IDS_SPONSORBLOCKS               10019
#define IDS_BACK                        10020
#define IDS_FOWARD                      10021
#define IDS_STOP                        10022
#define IDS_NEWS                        10023
#define IDS_ADRESS                      10024
#define IDS_NEWVOICEINSERT              10025
#define IDS_EDITSCHEDULE                10026
#define IDS_EDITLINEUP                  10027
#define IDS_LOCK                        10028
#define IDS_SCHEDULE                    10029
#define IDS_EXIT                        10030
#define IDS_EDIT                        10031
#define IDS_ANY                         10032
#define IDS_NEWLIST                     10033
#define IDS_RENAME                      10034
#define IDS_TITLE                       10100
#define IDS_DURATION                    10101
#define IDS_INTRO                       10102
#define IDS_STARTINGTIME                10103
#define IDS_FULLAUTO                    10104
#define IDS_LIVEASSIST                  10105
#define IDS_MANUAL                      10106
#define IDS_MUSIC                       10107
#define IDS_JINGLES                     10108
#define IDS_TRAFFIC                     10109
#define IDS_CARTWALL                    10110
#define IDS_VIDEOLINEUP                 10110
#define IDS_LINEUP                      10111
#define IDS_PRODUCER                    10112
#define IDS_MUSIC_DISCOGRAPHY           10113
#define IDS_MUSIC_PLAYLIST              10114
#define IDS_MUSIC_CATEGORY              10115
#define IDS_MUSIC_SEARCH                10116
#define IDS_PRODUCER_SOUNDRECORDER      10117
#define IDS_PRODUCER_MUSICEDITING       10118
#define IDS_PRODUCER_PROGRAMMING        10119
#define IDS_DEADLINE                    10120
#define IDS_TRAFFIC_SPONSORS            10121
#define IDS_TRAFFIC_BLOCKS              10122
#define IDS_TRAFFIC_BUMPED              10123
#define IDS_VOICEINSERT                 10124
#define IDS_ARTIST                      10125
#define IDS_SONGTITLE                   10126
#define IDS_SOUNDFILE                   10127
#define IDS_CATEGORY                    10128
#define IDS_PLAYLIST                    10129
#define IDS_EXPRESSION                  10130
#define IDS_LENGTH                      10131
#define IDS_INTROT                      10132
#define IDS_RYTHM                       10133
#define IDS_CDTITLE                     10134
#define IDS_RECORDINGDATE               10135
#define IDS_RECORDLABEL                 10136
#define IDS_LYRICS                      10137
#define IDS_MUSICCOMPOSER               10138
#define IDS_MUSICPRODUCER               10139
#define IDS_STUDIO                      10140
#define IDS_MUSICIANS                   10141
#define IDS_REMARKS                     10142
#define IDS_JANUARY                     10143
#define IDS_FEBRUARY                    10144
#define IDS_MARCH                       10145
#define IDS_APRIL                       10146
#define IDS_MAY                         10147
#define IDS_JUNE                        10148
#define IDS_JULY                        10149
#define IDS_AUGUST                      10150
#define IDS_SEPTEMBER                   10151
#define IDS_OCTOBER                     10152
#define IDS_NOVEMBER                    10153
#define IDS_DECEMBER                    10154
#define IDS_DATE                        10155
#define IDS_AIRED                       10156
#define IDS_RMS                         10157
#define IDS_INTERNET                    10158
#define IDS_TALENT                      10159
#define IDS_PATH                        10160
#define IDS_FILE                        10161
#define IDS_TIMESIGNAL                  10162
#define IDS_UNLISTED                    10163
#define IDS_CATEGORIES                  10164
#define IDS_TYPE                        10165
#define IDS_JINGLES_FULLLIST            10166
#define IDS_JINGLES_PLAYLIST            10167
#define IDS_JINGLES_EDIT                10168
#define IDS_SURVEILLANCE                10169
#define IDS_ERROR_OLEINITFAILED         11000
#define IDS_NOBLOCK                     12000
#define IDS_NOPROG                      12001
#define IDS_NEXTBLOCK                   12002
#define IDS_NEXTPROG                    12003
#define IDS_LINEUPLENGTH                12004
#define IDS_NOWSHOWING                  12005
#define IDS_NEWCATEGORY                 13000
#define IDS_NEWEXPRESSION               13001
#define IDS_NEWRECORD                   13002
#define IDS_NEWLABEL                    13003
#define IDS_MENUSTART                   13004
#define IDS_MENUFADEIN                  13005
#define IDS_MENUINTRO                   13006
#define IDS_MENUFADEOUT                 13007
#define IDS_MENUMIX                     13008
#define IDS_MENUEND                     13009
#define IDS_MENULOOPA                   13010
#define IDS_MENULOOPB                   13011
#define IDS_SONGMANDATORY               13012
#define IDS_STARTEXACT                  13013
#define IDS_ENDEXACT                    13014
#define IDS_NOTEXACTLY                  13015
#define IDS_MENULINEUP                  13016
#define IDS_MENUDELAY1                  13017
#define IDS_MENUDELAY2                  13018
#define IDS_MENUDELAY5                  13019
#define IDS_INFOCARTWALL                13020
#define IDS_CONFIRMNEWCARTWALL          13021
#define IDS_CARTWALLEXISTS              13022
#define IDS_MENUSKIPBLOCK               13023
#define IDS_MENUSKIPSCHEDULE            13024
#define IDS_FORMAT_SCHEDULETO           13025
#define IDS_CONFIRMRECORDING            13026
#define IDS_HASPERROR                   13027
#define IDS_LOGON                       13028
#define IDS_CONFIRMMUSICREMOVAL         13029
#define IDS_ARTISTNOTFOUND              13030
#define IDS_NOARTIST                    13031
#define IDS_NOTITLE                     13032
#define IDS_COULDNOTCHANGEFILENAME      13033
#define IDS_NOTLISTED                   13034
#define IDS_CONFIRMFILEDELETE           13035
#define IDS_NEWTYPEOFJINGLE             13036
#define IDS_CONFIRJINGLEREMOVE          13037
#define IDS_NEWJINGLEPLAYLIST           13038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
