//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Traffic.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_TRAFFITYPE                  129
#define IDB_TOOL_NEWSPOT                130
#define IDB_TOOL_EDIT_SPOT              131
#define IDB_TOOL_CUT                    132
#define IDB_TOOL_EDIT                   133
#define IDB_TREE_SPOT                   134
#define IDB_TREE_FOLDER_SPOT            135
#define IDB_TOOL_NEWTRAFFICSCHEDULE     136
#define IDB_TREE_FOLDER_SCHEDULE        137
#define IDB_TREE_SCHEDULE               138
#define IDD_SCHEDULE_SPOTS              139
#define IDB_TREE_SOUNDRECORDING         139
#define IDB_TOOL_QUERYBLOCKS            140
#define IDB_TREE_RECORDINGTASK          141
#define IDD_SCHEDULE_SPOTS_DETAIL       142
#define IDB_CONTAINER_JINGLES           142
#define IDD_SCHEDULE_BLOCKS             143
#define IDD_SCHEDULE_CLOCKS_DETAIL      144
#define IDB_TREE_JINGLE                 145
#define IDD_SPOT                        146
#define IDB_RECOFF                      147
#define IDB_PLAY                        148
#define IDD_RADIOSTATION                148
#define IDD_SPONSOR                     149
#define IDB_TOOL_PFL                    150
#define IDB_STOP                        151
#define IDB_TOOL_NEWSOUND               152
#define IDB_TREE_USER                   153
#define IDB_TOOL_NEWRM                  154
#define IDB_TREE_RM                     156
#define IDB_TREE_FOLDER_RM              157
#define IDD_RECORDINGTASK               158
#define IDB_CONTAINER_TRAFFIC           158
#define IDB_TREE_TEXT                   159
#define IDB_TREE_FOLDER_TEXT            160
#define IDB_TOOL_NEWTEXT                161
#define IDB_TOOL_NEWCARTWALL            162
#define IDB_TREE_CARTWALL               163
#define IDB_TOOL_INFO                   164
#define IDB_REC                         181
#define IDB_PAUSE_BIG                   184
#define IDB_CONTAINER_MUSIC             185
#define IDB_CONTAINER_VOICEINSERT       191
#define IDB_CONTAINER_RMS               201
#define IDD_CUSTOMER                    202
#define IDS_TOOL_NEWSPOT                512
#define IDS_TOOL_EDIT                   513
#define IDS_TOOL_CUT                    514
#define IDS_TOOL_NEWTRAFFICSCHEDULE     515
#define IDS_TOOL_QUERYBLOCKS            516
#define IDS_TOOL_NEWSOUND               517
#define IDS_TOOL_PFL                    518
#define IDS_TOOL_NEWRM                  519
#define IDS_TOOL_NEWTEXT                520
#define IDS_TOOL_NEWLINEUP              521
#define IDS_TOOL_TRAFFICLIST            522
#define IDC_RADIOSTATION                1000
#define IDD_SCHEDULE_MAIN               1001
#define IDC_CUSTOMER                    1001
#define IDC_STARTINGDATE                1002
#define IDC_SPOTNAME                    1002
#define IDC_STARTINGHOUR                1003
#define IDC_BYDATE                      1004
#define IDC_CUSTOMER_NAME               1005
#define IDC_BYNUMBER                    1005
#define IDC_CUSTOMER_ADRESS             1006
#define IDC_ENDINGDATE                  1006
#define IDC_CUSTOMER_ZIP                1007
#define IDC_FINALHOUR                   1007
#define IDC_CUSTOMER_PHONE              1008
#define IDC_NUMBER                      1008
#define IDC_CUSTOMER_FAX                1009
#define IDC_BYINSERT                    1009
#define IDC_CUSTOMER_EMAIL              1010
#define IDC_BYCONTRACT                  1010
#define IDC_CUSTOMER_WWW                1011
#define IDC_VALUE                       1011
#define IDC_CUSTOMER_CONTACT            1012
#define IDC_SPOTS                       1012
#define IDC_VALUE2                      1012
#define IDC_PI                          1012
#define IDC_CUSTOMER_FN                 1013
#define IDC_LIST2                       1013
#define IDC_CUSTOMER_BUSINESS           1014
#define IDC_BUTTON1                     1014
#define IDC_CUSTOMER_AGENCY             1015
#define IDC_BUTTON2                     1015
#define IDC_CUSTOMER_SALES              1016
#define IDC_BUTTON3                     1016
#define IDC_CUSTOMER_OBS                1017
#define IDC_NAME                        1017
#define IDC_CUSTOMER_NAME2              1018
#define IDC_CUSTOMER_NUMBER             1019
#define IDC_CUSTOMER_CELPHONE           1020
#define IDC_CUSTOMER_FN2                1021
#define IDC_SUN                         1023
#define IDC_BLOCKS                      1024
#define IDC_SELECTED                    1025
#define IDC_MON                         1028
#define IDC_TUE                         1029
#define IDC_WED                         1030
#define IDC_THU                         1031
#define IDC_FRI                         1032
#define IDC_SAT                         1033
#define IDC_BLOCKTREE                   1034
#define IDC_BUSINESS                    1037
#define IDC_AGENCY                      1038
#define IDC_VOICE                       1039
#define IDC_OBS                         1040
#define IDC_PATH                        1041
#define IDC_FILENAME                    1042
#define IDC_TIMERS                      1049
#define IDC_SPONSOR_STARTINGDATE        1053
#define IDC_SPONSOR_ENDINGDATE          1054
#define IDC_TASKNAME                    1054
#define IDC_TALENT                      1055
#define IDC_TASKDEADLINE                1056
#define IDC_TASK                        1057
#define IDC_STANDARDLENGTH              1058
#define IDS_TRAFFICSCHEDULE             2048
#define IDS_CUSTOMERSPOTS               2049
#define IDS_SPOTSTOSCHEDULE             2050
#define IDS_AIRINGPERIOD                2051
#define IDS_AIRINGDAYS                  2052
#define IDS_SUN                         2053
#define IDS_MON                         2054
#define IDS_TUE                         2055
#define IDS_WED                         2056
#define IDS_THU                         2057
#define IDS_FRI                         2058
#define IDS_SAT                         2059
#define IDS_BLOCKS                      2060
#define IDS_SELECTEDBLOCKS              2061
#define IDS_POSITION                    2062
#define IDS_SPOTSNUMBER                 2063
#define IDS_SPOTSLENGTH                 2064
#define IDS_BLOCK                       2065
#define IDS_EMPTYSLOT                   2066
#define IDS_REFRESH                     2067
#define IDS_SPONSORS                    2068
#define IDS_RECORDINGS                  2069
#define IDS_VOICEINSERT                 2070
#define IDS_TIMESIGNAL                  2071
#define IDS_FORMAT_FROMTO               4096
#define IDS_MENUSTART                   6146
#define IDS_MENUFADEIN                  6147
#define IDS_MENUINTRO                   6148
#define IDS_MENUFADEOUT                 6149
#define IDS_MENUMIX                     6150
#define IDS_MENUEND                     6151
#define IDS_MENULOOPA                   6152
#define IDS_MENULOOPB                   6153
#define IDS_CONFIRMSCHEDULEREMOVE       8192
#define IDS_CONFIRMSPONSORREMOVE        8193
#define IDS_CANTDELETECUSTOMER          8194
#define IDS_CONFIRMCUSTOMERREMOVE       8195
#define IDS_CONFIRMSPOTREMOVE           8196
#define IDS_NEWCUSTOMER                 8197
#define IDS_NEWBUSINESS                 8198
#define IDS_NEWAGENCY                   8199
#define IDS_NEWVOICE                    8200
#define IDS_NEWSALESMAN                 8201
#define IDS_SPONSORALLREADYEXISTS       8202
#define IDS_CONFIRMREMOVERECORDINGTASK  8203
#define IDS_CONFIRMRECORDING            8204
#define ID_TRAFFIC                      32771
#define ID_ONAIR_TRAFFIC                32772
#define ID_VIEW_AGENCY                  32774
#define ID_VIEW_SALESMAN                32775
#define ID_RECORDINGTASK                32776
#define ID_VIEW_VERTICAL                32777
#define ID_VIEW_HORIZONTAL              32778
#define ID_HELP_HELP                    32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
